### ISSUE TITLE
about this paper

### ISSUE THREAD

**Issue by only-yipie** [haoxiangsnr/SA-and-cGAN-for-SE#1]
您好，麻烦请问一下，这篇文章是已经发表了吗？想要学习一下，但是并没有搜到。谢谢赐教！

**Comment by haoxiangsnr** [comment]
已经投稿到了 ICASSP 2020，感谢您的关注！

**Comment by only-yipie** [comment]
您好，您有打算arvix上放您的论文吗?是这样的，因为我最近也打算用self attention gan做语音增强，担心工作和您的重复了，所以方便和您交流一下思路吗?


 
---Original---

**Comment by haoxiangsnr** [comment]
哈哈，文章仍然在审稿阶段，不太确定是否会误导大家，所以暂时就不放在 arXiv.org 上了。

思路说起来不值一提，是一篇堆性能的文章。我在深层 ResNet 中嵌入了 Self-attention Layer（用法类似图像中的 Non-local），之后引入对抗的方式进行训练。除了展示略有提升的结果外，还做了可视化的分析。
